window.ZentraAiRegistry = {
  disclaimer:
    "Here you can use an ai by providing an api key. We also want to clarify that we will never ever save your api key.",
  providers: [
    {
      id: "groq",
      name: "Groq (free)",
      models: [
        "llama-3.3-70b-versatile",
        "llama-3.1-8b-instant",
        "mixtral-8x7b-32768",
        "gemma2-9b-it",
      ],
      keyLabel: "Groq API key",
      keyHelp:
        "Go to console.groq.com, sign up free, open API Keys, create a key, and paste it here.",
      keyUrl: "https://console.groq.com/keys",
    },
    {
      id: "openai",
      name: "OpenAI",
      models: ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini", "gpt-4.1", "o3-mini"],
      keyLabel: "OpenAI API key",
      keyHelp: "Go to platform.openai.com/api-keys, create a key, and paste it here.",
      keyUrl: "https://platform.openai.com/api-keys",
    },
    {
      id: "openrouter",
      name: "OpenRouter",
      models: [
        "openai/gpt-4o-mini",
        "anthropic/claude-3.5-sonnet",
        "google/gemini-2.0-flash-001",
        "meta-llama/llama-3.3-70b-instruct",
        "deepseek/deepseek-chat",
      ],
      keyLabel: "OpenRouter API key",
      keyHelp: "Go to openrouter.ai/keys, create a key, and paste it here.",
      keyUrl: "https://openrouter.ai/keys",
    },
    {
      id: "anthropic",
      name: "Anthropic",
      models: [
        "claude-3-5-haiku-latest",
        "claude-3-5-sonnet-latest",
        "claude-3-opus-latest",
      ],
      keyLabel: "Anthropic API key",
      keyHelp: "Go to console.anthropic.com/settings/keys, create a key, and paste it here.",
      keyUrl: "https://console.anthropic.com/settings/keys",
    },
    {
      id: "gemini",
      name: "Google Gemini",
      models: ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro"],
      keyLabel: "Gemini API key",
      keyHelp: "Go to aistudio.google.com/apikey, create a key, and paste it here.",
      keyUrl: "https://aistudio.google.com/apikey",
    },
    {
      id: "mistral",
      name: "Mistral",
      models: ["mistral-small-latest", "mistral-large-latest", "open-mistral-nemo"],
      keyLabel: "Mistral API key",
      keyHelp: "Go to console.mistral.ai/api-keys, create a key, and paste it here.",
      keyUrl: "https://console.mistral.ai/api-keys/",
    },
    {
      id: "deepseek",
      name: "DeepSeek",
      models: ["deepseek-chat", "deepseek-reasoner"],
      keyLabel: "DeepSeek API key",
      keyHelp: "Go to platform.deepseek.com/api_keys, create a key, and paste it here.",
      keyUrl: "https://platform.deepseek.com/api_keys",
    },
    {
      id: "together",
      name: "Together AI",
      models: [
        "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "Qwen/Qwen2.5-72B-Instruct-Turbo",
        "mistralai/Mixtral-8x7B-Instruct-v0.1",
      ],
      keyLabel: "Together API key",
      keyHelp: "Go to api.together.xyz/settings/api-keys, create a key, and paste it here.",
      keyUrl: "https://api.together.xyz/settings/api-keys",
    },
    {
      id: "cohere",
      name: "Cohere",
      models: ["command-r-plus", "command-r", "command-light"],
      keyLabel: "Cohere API key",
      keyHelp: "Go to dashboard.cohere.com/api-keys, create a key, and paste it here.",
      keyUrl: "https://dashboard.cohere.com/api-keys",
    },
    {
      id: "perplexity",
      name: "Perplexity",
      models: ["sonar", "sonar-pro"],
      keyLabel: "Perplexity API key",
      keyHelp: "Go to perplexity.ai/settings/api, create a key, and paste it here.",
      keyUrl: "https://www.perplexity.ai/settings/api",
    },
    {
      id: "xai",
      name: "xAI",
      models: ["grok-2-latest", "grok-2-vision-latest"],
      keyLabel: "xAI API key",
      keyHelp: "Go to console.x.ai, create an API key, and paste it here.",
      keyUrl: "https://console.x.ai/",
    },
  ],
};
